[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0d1b2a"        # Azul muy oscuro pero no negro
secondaryBackgroundColor = "#415a77" # Azul grisáceo claro para paneles
textColor = "#e0e0e0"
font = "sans serif"
