[theme]
primaryColor = "#004080"       # Blau fosc professional
backgroundColor = "#f5f7fa"    # Gris clar suau
secondaryBackgroundColor = "#e1e5ea"
textColor = "#333333"          # Gris molt fosc per textos
font = "sans serif"
