[theme]
primaryColor = "#1f77b4"                  # Azul elegante para botones y highlights
backgroundColor = "#2e2e2e"               # Gris oscuro suave, nada de negro puro
secondaryBackgroundColor = "#3c3c3c"      # Gris un poco más claro para paneles
textColor = "#e0e0e0"                     # Gris claro para texto, buena legibilidad
font = "sans serif"
