[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"           # Fondo blanco puro
secondaryBackgroundColor = "#f0f4f8" # Paneles azul muy claro
textColor = "#0c1a2b"                 # Texto azul oscuro
font = "sans serif"
