[theme]
primaryColor = "#1f77b4"
backgroundColor = "#121212"      # Fondo negro oscuro
secondaryBackgroundColor = "#f0f0f0" # Gris muy oscuro para paneles
textColor = "#e0e0e0"            # Texto gris claro
font = "sans serif"
